// Frontend-only display labels. Keys reference canonical Composer IDs; values are never submitted.
const HE_TAXONOMY_LABELS = Object.freeze(
{
  "family/photography": "צילום",
  "photography/photorealistic": "פוטוריאליסטי",
  "photography/portrait": "דיוקן",
  "photography/environmental-portrait": "דיוקן סביבתי",
  "photography/studio-portrait": "דיוקן סטודיו",
  "photography/headshot": "דיוקן ראש",
  "photography/fashion": "אופנה",
  "photography/editorial": "דיוקן מערכתי",
  "photography/lifestyle": "אורח חיים",
  "photography/documentary": "תיעודי",
  "photography/photojournalistic": "צילום עיתונאי",
  "photography/street": "רחוב",
  "photography/travel": "נסיעות",
  "photography/landscape": "נוף",
  "photography/nature": "טבע",
  "photography/wildlife": "חיות בר",
  "photography/architectural": "אדריכלות",
  "photography/interior": "פנים",
  "photography/real-estate": "נדל״ן",
  "photography/product": "מוצר",
  "photography/commercial-advertising": "פרסום מסחרי",
  "photography/food": "אוכל",
  "photography/still-life": "טבע דומם",
  "photography/macro": "מאקרו",
  "photography/close-up": "תקריב",
  "photography/sports-action": "ספורט/אקשן",
  "photography/automotive": "רכב",
  "photography/night": "לילה",
  "photography/low-light": "אור נמוך",
  "photography/long-exposure": "חשיפה ארוכה",
  "photography/aerial-drone": "אוויר/מל\"ט",
  "photography/underwater": "מתחת למים",
  "photography/black-and-white": "שחור־לבן",
  "photography/fine-art": "אמנות יפה",
  "photography/vintage": "וינטג'",
  "photography/analog-film": "סרט אנלוגי",
  "photography/instant-film": "סרט מיידי",
  "photography/cinematic": "קולנועי",
  "photography/high-key": "מפתח גבוה",
  "photography/low-key": "מפתח נמוך",
  "photography/minimalist": "מינימליסטי",
  "photography/surreal": "סוריאליסטי",
  "family/cinematic-film-still": "קולנוע / פריים מסרט",
  "cinematic-film-still/film-still": "סרט סטילס",
  "cinematic-film-still/feature-film-look": "מראה סרט עלילתי",
  "cinematic-film-still/dramatic": "דרמטי",
  "cinematic-film-still/epic": "אפוס",
  "cinematic-film-still/intimate": "אינטימי",
  "cinematic-film-still/noir": "נואר",
  "cinematic-film-still/sci-fi": "מדע בדיוני",
  "cinematic-film-still/fantasy": "פנטזיה",
  "cinematic-film-still/period-film": "תקופה-סרט",
  "cinematic-film-still/documentary-film": "סרט תיעודי",
  "cinematic-film-still/commercial-film": "סרט מסחרי",
  "cinematic-film-still/music-video": "מוזיקה-קליפ",
  "cinematic-film-still/storyboard-frame": "מסגרת לוח סיפור",
  "cinematic-film-still/anamorphic": "אנמורפי",
  "cinematic-film-still/shallow-depth": "עומק רדוד",
  "cinematic-film-still/wide-establishing-shot": "זריקה רחבה",
  "cinematic-film-still/close-cinematic-portrait": "דיוקן קולנועי קרוב",
  "family/illustration": "איור",
  "illustration/digital": "דיגיטלי",
  "illustration/editorial": "מאמר מערכת",
  "illustration/childrens-book": "ספר ילדים",
  "illustration/storybook": "ספר סיפורים",
  "illustration/educational": "חינוכית",
  "illustration/technical": "טכני",
  "illustration/scientific": "מדעי",
  "illustration/botanical": "בוטני",
  "illustration/natural-history": "היסטוריה-טבע",
  "illustration/fashion": "אופנה",
  "illustration/architectural": "אדריכלות",
  "illustration/travel": "נסיעות",
  "illustration/food": "אוכל",
  "illustration/decorative": "דקורטיבי",
  "illustration/line": "קו",
  "illustration/ink": "דיו",
  "illustration/pen-and-ink": "עט-ודיו",
  "illustration/colored-pencil": "עיפרון צבעוני",
  "illustration/marker": "מרקר",
  "illustration/flat": "שטוח",
  "illustration/minimal": "מינימום",
  "illustration/geometric": "גיאומטרי",
  "illustration/textured": "מרקם",
  "illustration/hand-drawn": "מצויר ביד",
  "illustration/retro": "רטרו",
  "illustration/vintage": "וינטג'",
  "illustration/whimsical": "גחמני",
  "illustration/cute": "חמוד",
  "illustration/detailed-fantasy": "פנטזיה מפורטת",
  "illustration/sci-fi": "מדע בדיוני",
  "family/fine-art-traditional-media": "אמנות יפה / מדיה מסורתית",
  "fine-art-traditional-media/oil": "נפט",
  "fine-art-traditional-media/watercolor": "צבעי מים",
  "fine-art-traditional-media/acrylic": "אקריליק",
  "fine-art-traditional-media/gouache": "גואש",
  "fine-art-traditional-media/tempera": "טמפרה",
  "fine-art-traditional-media/fresco-inspired": "בהשראת פרסקו",
  "fine-art-traditional-media/pastel": "פסטל",
  "fine-art-traditional-media/soft-pastel": "פסטל רך",
  "fine-art-traditional-media/oil-pastel": "פסטל שמן",
  "fine-art-traditional-media/charcoal": "פחם",
  "fine-art-traditional-media/graphite": "גרפיט",
  "fine-art-traditional-media/colored-pencil": "עיפרון צבעוני",
  "fine-art-traditional-media/pen": "עט",
  "fine-art-traditional-media/ink-wash": "שטיפת דיו",
  "fine-art-traditional-media/brush-and-ink": "מברשת ודיו",
  "fine-art-traditional-media/chalk": "גיר",
  "fine-art-traditional-media/crayon": "עפרון",
  "fine-art-traditional-media/mixed-media": "מדיה מעורבת",
  "fine-art-traditional-media/collage": "קולאז'",
  "fine-art-traditional-media/paper-cut": "חיתוך נייר",
  "fine-art-traditional-media/printmaking": "יצירת דפוס",
  "fine-art-traditional-media/woodcut": "חיתוך עץ",
  "fine-art-traditional-media/linocut": "חיתוך לינו",
  "fine-art-traditional-media/etching": "תחריט",
  "fine-art-traditional-media/engraving": "חריטה",
  "fine-art-traditional-media/lithograph": "ליטוגרפיה",
  "fine-art-traditional-media/screen-print": "הדפסת מסך",
  "fine-art-traditional-media/pointillist": "פונטיליסט",
  "fine-art-traditional-media/impressionistic": "אימפרסיוניסטי",
  "fine-art-traditional-media/expressionistic": "אקספרסיוניסטי",
  "fine-art-traditional-media/abstract": "מופשט",
  "fine-art-traditional-media/minimalist": "מינימליסטי",
  "fine-art-traditional-media/folk-art-inspired": "השראת אמנות עממית",
  "fine-art-traditional-media/mural-like": "דמוי קיר",
  "family/3d-cgi": "תלת־ממד / CGI",
  "3d-cgi/general-3d": "תלת מימד כללי",
  "3d-cgi/photorealistic-3d": "תלת מימד פוטוריאליסטי",
  "3d-cgi/stylized-3d": "תלת מימד מסוגנן",
  "3d-cgi/cinematic-3d": "תלת מימד קולנועי",
  "3d-cgi/character": "דמות",
  "3d-cgi/environment": "סביבה",
  "3d-cgi/product-render": "עיבוד מוצר",
  "3d-cgi/architectural-visualization": "הדמיה אדריכלית",
  "3d-cgi/interior-visualization": "הדמיית פנים",
  "3d-cgi/automotive": "רכב",
  "3d-cgi/hard-surface": "משטח קשה",
  "3d-cgi/soft-stylized": "מסוגנן רך",
  "3d-cgi/clay": "חימר",
  "3d-cgi/claymation-like": "דמוי חימר",
  "3d-cgi/toy-like": "דמוי צעצוע",
  "3d-cgi/miniature-diorama": "מיניאטורה/דיורמה",
  "3d-cgi/low-poly": "פולי נמוך",
  "3d-cgi/high-poly": "פולי גבוה",
  "3d-cgi/isometric": "איזומטרי",
  "3d-cgi/voxel": "Voxel",
  "3d-cgi/papercraft": "מלאכת נייר",
  "3d-cgi/plastic": "פלסטיק",
  "3d-cgi/glass": "זכוכית",
  "3d-cgi/metallic": "מתכתי",
  "3d-cgi/ceramic": "קרמיקה",
  "3d-cgi/fabric-felt": "בד/לבד",
  "3d-cgi/inflatable": "מתנפח",
  "3d-cgi/holographic": "הולוגרפית",
  "3d-cgi/neon": "ניאון",
  "3d-cgi/abstract-3d": "תלת מימד מופשט",
  "3d-cgi/motion-design-still": "סטילס עיצוב תנועה",
  "3d-cgi/game-asset": "נכס משחק",
  "3d-cgi/game-environment": "סביבת משחק",
  "family/graphic-design": "עיצוב גרפי",
  "graphic-design/general": "כללי",
  "graphic-design/poster": "פוסטר",
  "graphic-design/advertising-poster": "כרזה פרסומית",
  "graphic-design/event-poster": "כרזה לאירוע",
  "graphic-design/movie-poster-like": "דמוי סרט",
  "graphic-design/book-cover": "כריכת הספר",
  "graphic-design/album-cover": "כריכת האלבום",
  "graphic-design/magazine-cover": "כריכת מגזין",
  "graphic-design/editorial-layout": "מתווה עריכה",
  "graphic-design/social-graphic": "גרפיקה חברתית",
  "graphic-design/banner": "באנר",
  "graphic-design/flyer": "עלון",
  "graphic-design/brochure": "חוברת",
  "graphic-design/packaging-concept": "קונספט אריזה",
  "graphic-design/label": "תווית",
  "graphic-design/logo-concept": "קונספט הלוגו",
  "graphic-design/brand-mark": "סימן מותג",
  "graphic-design/icon": "סמל",
  "graphic-design/icon-set": "ערכת אייקונים",
  "graphic-design/sticker": "מדבקה",
  "graphic-design/badge-emblem": "תג/סמל",
  "graphic-design/signage": "שילוט",
  "graphic-design/typography-led": "הובלת טיפוגרפיה",
  "graphic-design/minimal": "מינימום",
  "graphic-design/grid-swiss-like": "דמוי רשת/שוויצרי",
  "graphic-design/geometric": "גיאומטרי",
  "graphic-design/retro": "רטרו",
  "graphic-design/vintage-print": "הדפס וינטג'",
  "graphic-design/futuristic": "עתידני",
  "graphic-design/gradient": "שיפוע",
  "graphic-design/collage": "קולאז'",
  "family/vector-flat-art": "וקטור / אמנות שטוחה",
  "vector-flat-art/vector-style": "בסגנון וקטור",
  "vector-flat-art/flat-vector": "וקטור שטוח",
  "vector-flat-art/minimal-vector": "וקטור מינימלי",
  "vector-flat-art/geometric-vector": "וקטור גיאומטרי",
  "vector-flat-art/outline": "מתווה",
  "vector-flat-art/filled-icon": "סמל מלא",
  "vector-flat-art/monoline": "מונולין",
  "vector-flat-art/duotone": "דואוטון",
  "vector-flat-art/infographic": "אינפוגרפיקה",
  "vector-flat-art/mascot": "קמע",
  "vector-flat-art/sticker": "מדבקה",
  "vector-flat-art/logo-mark-concept": "קונספט סימן לוגו",
  "vector-flat-art/pictogram": "פיקטוגרם",
  "vector-flat-art/map-like": "דמוי מפה",
  "vector-flat-art/isometric-vector": "וקטור איזומטרי",
  "vector-flat-art/flat-character": "דמות שטוחה",
  "family/cartoon-animation": "קריקטורה / אנימציה",
  "cartoon-animation/general-cartoon": "קריקטורה כללית",
  "cartoon-animation/2d": "2D",
  "cartoon-animation/3d": "תלת מימד",
  "cartoon-animation/tv-animation-look": "מראה טלוויזיה-אנימציה",
  "cartoon-animation/feature-animation-look": "מראה תכונה-אנימציה",
  "cartoon-animation/cute": "חמוד",
  "cartoon-animation/exaggerated": "מוגזם",
  "cartoon-animation/minimal": "מינימום",
  "cartoon-animation/flat": "שטוח",
  "cartoon-animation/portrait": "דיוקן",
  "cartoon-animation/environment": "סביבה",
  "cartoon-animation/mascot": "קמע",
  "cartoon-animation/infographic": "אינפוגרפיקה",
  "cartoon-animation/sticker": "מדבקה",
  "cartoon-animation/stop-motion-inspired": "בהשראת סטופ מושן",
  "cartoon-animation/puppet-inspired": "בהשראת בובות",
  "family/comic-sequential-art": "קומיקס / אמנות רציפה",
  "comic-sequential-art/general-comic": "קומיקס כללי",
  "comic-sequential-art/western-comic-visual-language": "שפה חזותית מערבית-קומית",
  "comic-sequential-art/graphic-novel": "רומן גרפי",
  "comic-sequential-art/newspaper-strip": "רצועת עיתון",
  "comic-sequential-art/clean-line": "קו נקי",
  "comic-sequential-art/inked": "דיו",
  "comic-sequential-art/halftone": "חצי גוון",
  "comic-sequential-art/retro-pulp": "עיסת רטרו",
  "comic-sequential-art/superhero-comic-like": "דמוי גיבורי-על",
  "comic-sequential-art/noir": "נואר",
  "comic-sequential-art/sci-fi": "מדע בדיוני",
  "comic-sequential-art/fantasy": "פנטזיה",
  "comic-sequential-art/childrens": "ילדים",
  "comic-sequential-art/single-panel": "פאנל בודד",
  "comic-sequential-art/multi-panel": "ריבוי פאנלים רק אם נתמך",
  "family/anime-manga": "אנימה / מנגה",
  "anime-manga/anime-inspired": "בהשראת אנימה",
  "anime-manga/manga-inspired": "בהשראת מנגה",
  "anime-manga/anime-cinematic": "אנימה קולנועית",
  "anime-manga/anime-portrait": "דיוקן אנימה",
  "anime-manga/anime-environment": "סביבת אנימה",
  "anime-manga/anime-fantasy": "פנטזיה של אנימה",
  "anime-manga/anime-sci-fi": "מדע בדיוני אנימה",
  "anime-manga/chibi-inspired": "בהשראת צ'יבי",
  "anime-manga/manga-ink": "דיו מנגה",
  "anime-manga/manga-screentone": "גוון מסך מנגה",
  "anime-manga/shoujo-like-properties": "מאפיינים דמויי שוג'ו",
  "anime-manga/shounen-like-properties": "נכסים דמויי שונן",
  "anime-manga/seinen-like-properties": "מאפיינים דמויי סיינן",
  "anime-manga/retro-animation": "אנימציית רטרו",
  "family/concept-art": "אמנות קונספט",
  "concept-art/general": "כללי",
  "concept-art/character": "דמות",
  "concept-art/creature": "יצור",
  "concept-art/environment": "סביבה",
  "concept-art/prop": "פרוב",
  "concept-art/vehicle": "רכב",
  "concept-art/architecture": "אדריכלות",
  "concept-art/interior": "פנים",
  "concept-art/costume": "תחפושת",
  "concept-art/keyframe": "מסגרת מפתח",
  "concept-art/mood-painting": "ציור מצב רוח",
  "concept-art/matte-painting-like": "דמוי ציור מט",
  "concept-art/fantasy": "פנטזיה",
  "concept-art/sci-fi": "מדע בדיוני",
  "concept-art/post-apocalyptic": "פוסט אפוקליפטי",
  "concept-art/historical": "היסטורי",
  "concept-art/futuristic": "עתידני",
  "concept-art/world-building": "בניין עולם",
  "family/fantasy": "פנטזיה",
  "fantasy/general": "כללי",
  "fantasy/epic": "אפוס",
  "fantasy/dark": "חושך",
  "fantasy/light": "אור",
  "fantasy/fairy-tale": "אגדה",
  "fantasy/mythic": "מיתי",
  "fantasy/enchanted-forest": "יער קסום",
  "fantasy/magical-realism": "ריאליזם קסום",
  "fantasy/landscape": "נוף",
  "fantasy/city": "עיר",
  "fantasy/character": "דמות",
  "fantasy/creature": "יצור",
  "fantasy/artifact": "חפץ",
  "fantasy/dreamlike": "חלומית",
  "fantasy/whimsical": "גחמני",
  "family/sci-fi-futuristic": "מדע בדיוני / עתידני",
  "sci-fi-futuristic/general": "כללי",
  "sci-fi-futuristic/hard-sci-fi": "מדע בדיוני קשיח",
  "sci-fi-futuristic/space-opera": "אופרת חלל",
  "sci-fi-futuristic/futuristic-city": "עיר עתידנית",
  "sci-fi-futuristic/futuristic-interior": "פנים עתידני",
  "sci-fi-futuristic/spaceship": "ספינת חלל",
  "sci-fi-futuristic/space-environment": "סביבת חלל",
  "sci-fi-futuristic/alien-world": "עולם זר",
  "sci-fi-futuristic/robotics": "רובוטיקה",
  "sci-fi-futuristic/cybernetic": "קיברנטי",
  "sci-fi-futuristic/cyberpunk": "סייברפאנק",
  "sci-fi-futuristic/solarpunk": "סולארפאנק",
  "sci-fi-futuristic/biopunk": "ביופאנק",
  "sci-fi-futuristic/retro-futurism": "רטרו-פוטוריזם",
  "sci-fi-futuristic/cassette-futurism": "קסטות-פוטוריזם",
  "sci-fi-futuristic/utopian": "אוטופי",
  "sci-fi-futuristic/dystopian": "דיסטופי",
  "sci-fi-futuristic/holographic": "הולוגרפית",
  "sci-fi-futuristic/neon": "ניאון",
  "sci-fi-futuristic/tech-interface-inspired": "בהשראת ממשק טכנולוגי",
  "family/architecture-interior": "אדריכלות / עיצוב פנים",
  "architecture-interior/exterior-visualization": "הדמיה חיצונית",
  "architecture-interior/interior-visualization": "הדמיה פנימית",
  "architecture-interior/residential": "מגורים",
  "architecture-interior/commercial": "מסחרי",
  "architecture-interior/hospitality": "אירוח",
  "architecture-interior/office": "משרד",
  "architecture-interior/retail": "קמעונאות",
  "architecture-interior/exhibition": "תערוכה",
  "architecture-interior/landscape-architecture": "אדריכלות נוף",
  "architecture-interior/urban-planning": "תכנון עירוני",
  "architecture-interior/conceptual": "רעיוני",
  "architecture-interior/futuristic": "עתידני",
  "architecture-interior/minimal": "מינימום",
  "architecture-interior/luxury-interior": "פנים יוקרתי",
  "architecture-interior/scandinavian-like": "דמוי סקנדינבי",
  "architecture-interior/industrial": "תעשייתי",
  "architecture-interior/rustic": "כפרי",
  "architecture-interior/modern": "מודרני",
  "architecture-interior/classical": "קלאסי",
  "architecture-interior/night": "לילה",
  "architecture-interior/daylight": "אור יום",
  "architecture-interior/axonometric-isometric": "אקסונומטרי/איזומטרי",
  "family/product-commercial": "מוצר / מסחרי",
  "product-commercial/studio-product": "מוצר סטודיו",
  "product-commercial/white-background": "רקע לבן",
  "product-commercial/lifestyle-product": "מוצר סגנון חיים",
  "product-commercial/hero-product": "מוצר גיבור",
  "product-commercial/luxury": "מותרות",
  "product-commercial/tech": "טק",
  "product-commercial/cosmetic": "קוסמטיקה",
  "product-commercial/food-package": "חבילת מזון",
  "product-commercial/beverage-package": "חבילת משקה",
  "product-commercial/jewelry": "תכשיטים",
  "product-commercial/watch": "צפו",
  "product-commercial/furniture": "ריהוט",
  "product-commercial/automotive": "רכב",
  "product-commercial/floating-product": "מוצר צף",
  "product-commercial/exploded-view-like": "דמוי תצוגה מפוצצת אם נתמך",
  "product-commercial/minimal-render": "עיבוד מינימלי",
  "product-commercial/dramatic-commercial": "פרסומת דרמטית",
  "product-commercial/e-commerce-like": "דומה למסחר אלקטרוני",
  "family/infographic-educational": "אינפוגרפיקה / חינוכי",
  "infographic-educational/general-infographic": "אינפוגרפיקה כללית",
  "infographic-educational/process": "תהליך",
  "infographic-educational/timeline": "ציר זמן",
  "infographic-educational/comparison": "השוואה",
  "infographic-educational/diagram-like": "דמוי דיאגרמה",
  "infographic-educational/educational-poster": "כרזה חינוכית",
  "infographic-educational/data-story": "סיפור נתונים",
  "infographic-educational/map-like": "דמוי מפה",
  "infographic-educational/technical-explainer": "הסבר טכני",
  "infographic-educational/step-by-step": "שלב אחר שלב",
  "infographic-educational/labeled-illustration": "איור עם תווית",
  "family/coloring-page-line-art": "דף צביעה / אמנות קווית",
  "coloring-page-line-art/simple": "פשוט",
  "coloring-page-line-art/detailed": "מפורט",
  "coloring-page-line-art/childrens": "ילדים",
  "coloring-page-line-art/intricate": "מסובך",
  "coloring-page-line-art/clean-black-outline": "מתאר שחור נקי",
  "coloring-page-line-art/thick-outline": "מתאר עבה",
  "coloring-page-line-art/thin-outline": "מתאר דק",
  "coloring-page-line-art/mandala-like": "דמוי מנדלה",
  "coloring-page-line-art/geometric": "גיאומטרי",
  "coloring-page-line-art/nature": "טבע",
  "coloring-page-line-art/architecture": "אדריכלות",
  "coloring-page-line-art/character": "דמות",
  "coloring-page-line-art/object": "חפץ",
  "coloring-page-line-art/printable-line-art": "אמנות קו להדפסה",
  "family/pixel-art": "פיקסל ארט",
  "pixel-art/general": "כללי",
  "pixel-art/character": "דמות",
  "pixel-art/portrait": "דיוקן",
  "pixel-art/environment": "סביבה",
  "pixel-art/landscape": "נוף",
  "pixel-art/icon": "סמל",
  "pixel-art/item-object": "פריט/חפץ",
  "pixel-art/isometric": "איזומטרי",
  "pixel-art/game-scene": "סצנת משחק",
  "pixel-art/ui-like-asset": "נכס דמוי ממשק משתמש",
  "family/isometric": "איזומטרי",
  "isometric/3d": "תלת מימד",
  "isometric/vector": "וקטור",
  "isometric/room": "חדר",
  "isometric/building": "בניין",
  "isometric/city": "עיר",
  "isometric/landscape": "נוף",
  "isometric/infographic": "אינפוגרפיקה",
  "isometric/product": "מוצר",
  "isometric/game-asset": "נכס משחק",
  "isometric/cutaway": "Cutaway אם נתמך",
  "family/low-poly-voxel-game-stylized": "Low-Poly / ווקסל / משחק מסוגנן",
  "low-poly-voxel-game-stylized/low-poly-object": "אובייקט נמוך פולי",
  "low-poly-voxel-game-stylized/low-poly-character": "תו פולי נמוך",
  "low-poly-voxel-game-stylized/low-poly-environment": "סביבת פולי נמוכה",
  "low-poly-voxel-game-stylized/low-poly-landscape": "נוף פולי נמוך",
  "low-poly-voxel-game-stylized/voxel-object": "אובייקט ווקסל",
  "low-poly-voxel-game-stylized/voxel-character": "דמות ווקסל",
  "low-poly-voxel-game-stylized/voxel-environment": "סביבת ווקסל",
  "low-poly-voxel-game-stylized/stylized-game-asset": "נכס משחק מסוגנן",
  "low-poly-voxel-game-stylized/stylized-game-environment": "סביבת משחק מסוגננת",
  "low-poly-voxel-game-stylized/stylized-game-character": "דמות משחק מסוגננת",
  "low-poly-voxel-game-stylized/diorama-game-scene": "סצנת משחק דיורמה",
  "family/paper-craft-handmade": "נייר / מלאכת יד",
  "paper-craft-handmade/papercraft": "נייר",
  "paper-craft-handmade/paper-cut": "חיתוך נייר",
  "paper-craft-handmade/layered-paper": "נייר שכבות",
  "paper-craft-handmade/origami-inspired": "בהשראת אוריגמי",
  "paper-craft-handmade/cardboard": "קרטון",
  "paper-craft-handmade/felt": "לבד",
  "paper-craft-handmade/fabric": "בד",
  "paper-craft-handmade/embroidery-like": "דמוי רקמה",
  "paper-craft-handmade/knitted-crocheted-like": "דמוי סרוג/סרוגה",
  "paper-craft-handmade/handmade-collage": "קולאז' בעבודת יד",
  "paper-craft-handmade/scrapbook": "אלבום",
  "paper-craft-handmade/wooden-toy": "צעצוע עץ",
  "paper-craft-handmade/ceramic-clay-craft": "מלאכת קרמיקה/חימר",
  "paper-craft-handmade/miniature-diorama": "דיורמה מיניאטורית",
  "family/icon-ui-asset": "אייקון / נכס ממשק",
  "icon-ui-asset/app-icon-concept": "קונספט אייקון אפליקציה",
  "icon-ui-asset/toolbar-icon": "סמל סרגל כלים",
  "icon-ui-asset/pictogram": "פיקטוגרם",
  "icon-ui-asset/flat-icon": "סמל שטוח",
  "icon-ui-asset/outline-icon": "סמל מתאר",
  "icon-ui-asset/filled-icon": "סמל מלא",
  "icon-ui-asset/duotone-icon": "סמל דואוטון",
  "icon-ui-asset/3d-icon": "סמל תלת מימד",
  "icon-ui-asset/clay-icon": "סמל חימר",
  "icon-ui-asset/glossy-icon": "סמל מבריק",
  "icon-ui-asset/sticker-icon": "סמל מדבקה",
  "icon-ui-asset/isometric-icon": "אייקון איזומטרי",
  "icon-ui-asset/game-inventory-icon": "סמל של מלאי משחקים",
  "family/pattern-decorative": "דוגמה / דקורטיבי",
  "pattern-decorative/seamless-pattern-like": "דמוי-דפוס ללא תפרים",
  "pattern-decorative/geometric": "גיאומטרי",
  "pattern-decorative/floral": "פרחוני",
  "pattern-decorative/botanical": "בוטני",
  "pattern-decorative/abstract": "מופשט",
  "pattern-decorative/textile-like": "דמוי טקסטיל",
  "pattern-decorative/wallpaper": "טפט",
  "pattern-decorative/ornamental": "נוי",
  "pattern-decorative/minimal": "מינימום",
  "pattern-decorative/retro": "רטרו",
  "pattern-decorative/futuristic": "עתידני",
  "family/abstract-experimental": "מופשט / ניסיוני",
  "abstract-experimental/general-abstract": "תקציר כללי",
  "abstract-experimental/geometric": "גיאומטרי",
  "abstract-experimental/organic": "אורגני",
  "abstract-experimental/fluid": "נוזל",
  "abstract-experimental/generative-art-like": "דמוי אמנות-גנרטיבית",
  "abstract-experimental/fractal-inspired": "בהשראת פרקטלים",
  "abstract-experimental/light-painting": "ציור אור",
  "abstract-experimental/color-field": "שדה צבע",
  "abstract-experimental/minimal": "מינימום",
  "abstract-experimental/surreal": "סוריאליסטי",
  "abstract-experimental/glitch": "תקלה",
  "abstract-experimental/datamosh-inspired-still": "דומם בהשראת דאטמוש",
  "abstract-experimental/holographic": "הולוגרפית",
  "abstract-experimental/iridescent": "ססגוני",
  "abstract-experimental/particle-based": "מבוסס חלקיקים",
  "family/retro-vintage": "רטרו / וינטג׳",
  "retro-vintage/general-vintage": "בציר כללי",
  "retro-vintage/retro-print": "הדפס רטרו",
  "retro-vintage/mid-century-like": "דומה לאמצע המאה",
  "retro-vintage/art-deco-like": "דמוי ארט דקו",
  "retro-vintage/art-nouveau-like": "דמוי אר-נובו",
  "retro-vintage/1950s-advertising": "פרסום של שנות החמישים",
  "retro-vintage/1960s-psychedelic": "פסיכדלי של שנות ה-60",
  "retro-vintage/1970s-print": "הדפס של שנות ה-70",
  "retro-vintage/1980s-neon": "ניאון של שנות השמונים",
  "retro-vintage/1990s-graphic": "גרפיקה של שנות ה-90",
  "retro-vintage/y2k-like": "דומה ל-Y2K",
  "retro-vintage/vintage-travel-poster": "פוסטר נסיעות וינטג'",
  "retro-vintage/vintage-scientific-illustration": "איור מדעי וינטג'",
  "retro-vintage/aged-paper": "נייר מיושן",
  "family/minimal-clean": "מינימלי / נקי",
  "minimal-clean/minimal-photography": "מינימום צילום",
  "minimal-clean/minimal-illustration": "איור מינימלי",
  "minimal-clean/minimal-graphic-design": "עיצוב גרפי מינימלי",
  "minimal-clean/minimal-3d": "מינימום תלת מימד",
  "minimal-clean/clean-product": "מוצר נקי",
  "minimal-clean/white-space-heavy": "לבן-חלל-כבד",
  "minimal-clean/monochrome": "מונוכרום",
  "minimal-clean/geometric": "גיאומטרי",
  "minimal-clean/soft-neutral": "נייטרלי רך",
  "family/surreal-dreamlike": "סוריאליסטי / חלומי",
  "surreal-dreamlike/surreal-photography": "צילום סוריאליסטי",
  "surreal-dreamlike/surreal-illustration": "איור סוריאליסטי",
  "surreal-dreamlike/dreamlike": "חלומית",
  "surreal-dreamlike/impossible-architecture": "ארכיטקטורה בלתי אפשרית",
  "surreal-dreamlike/floating-objects": "עצמים צפים",
  "surreal-dreamlike/scale-shift": "שינוי קנה מידה",
  "surreal-dreamlike/symbolic": "סמל",
  "surreal-dreamlike/soft-dreamscape": "נוף חלומי רך",
  "surreal-dreamlike/dark-dreamscape": "נוף חלומות אפל",
  "surreal-dreamlike/liminal-space": "לימינל-מרחב",
  "family/map-spatial-illustration": "מפה / איור מרחבי",
  "map-spatial-illustration/illustrated-map": "מפה מאוירת",
  "map-spatial-illustration/fantasy-map": "מפת פנטזיה",
  "map-spatial-illustration/tourist-map": "מפת תיירות",
  "map-spatial-illustration/city-map-like": "דמוי מפת עיר",
  "map-spatial-illustration/isometric-map": "מפה איזומטרית",
  "map-spatial-illustration/terrain-map-like": "דמוי מפת שטח",
  "map-spatial-illustration/treasure-map-like": "דמוי מפת אוצר",
  "map-spatial-illustration/diagrammatic-map": "מפה דיאגרמטית",
  "pixel-art/8-bit-inspired": "בהשראת 8 ביט",
  "pixel-art/16-bit-inspired": "בהשראת 16 ביט",
  "pixel-art/32-bit-inspired": "בהשראת 32 ביט"
}
);

export default HE_TAXONOMY_LABELS;

