#!/usr/bin/env python3
import argparse,pathlib
p=argparse.ArgumentParser(); p.add_argument('--install-root',required=True); p.add_argument('--storage',required=True); p.add_argument('--output',required=True); p.add_argument('--python',default='/usr/bin/python3'); p.add_argument('--compat-port',default='18192'); a=p.parse_args()
r=pathlib.Path(a.install_root); s=pathlib.Path(a.storage); o=pathlib.Path(a.output); o.mkdir(parents=True,exist_ok=True)
units={
'aag-chess-anythingllm-bridge.service':f'''[Unit]\nDescription=AAG Chess Puzzle AnythingLLM bridge\nAfter=default.target\n[Service]\nType=simple\nWorkingDirectory={r}/chess\nEnvironment=PYTHONPATH={r}/chess/src\nExecStart={a.python} -m aag_chess.anythingllm_bridge --socket {s}/aag-chess-puzzle/bridge.sock --output-root {s}/aag-chess-puzzle/outputs --private-root {s}/aag-chess-puzzle/private-solutions --timeout-seconds 240\nRestart=on-failure\nNoNewPrivileges=true\nPrivateTmp=true\nUMask=0077\n[Install]\nWantedBy=default.target\n''',
'aag-model-compatibility.service':f'''[Unit]\nDescription=AAG model-neutral compatibility boundary\nAfter=network.target\n[Service]\nType=simple\nExecStart={a.python} {r}/model-neutral-compatibility/server.py\nEnvironment=AAG_COMPAT_BIND=127.0.0.1\nEnvironment=AAG_COMPAT_PORT={a.compat_port}\nEnvironment=AAG_COMPAT_STORAGE={s}/aag-model-neutral-compatibility\nEnvironment=AAG_COMPAT_TOKEN_FILE={s}/aag-model-neutral-compatibility/proxy.token\nRestart=on-failure\nNoNewPrivileges=true\nPrivateTmp=true\nProtectSystem=strict\nProtectHome=read-only\nReadWritePaths={s}/aag-model-neutral-compatibility\nUMask=0077\n[Install]\nWantedBy=default.target\n'''}
units['aag-human-identity-bridge.service']=f'''[Unit]\nDescription=AAG Human Identity Contract B worker\n[Service]\nType=oneshot\nWorkingDirectory={r}/image-system\nEnvironment=AAG_IMAGE_PROJECT_ROOT={r}/image-system\nEnvironment=AAG_HUMAN_IDENTITY_RUNTIME={r}/image-system/human-identity\nEnvironment=AAG_HUMAN_IDENTITY_STATE_ROOT={s}/aag-human-identity-state\nEnvironment=AAG_IMAGE_AGENT_STATE_ROOT={s}/aag-image-agent-state\nEnvironment=AAG_OUTPUT_ROOT={r}/outputs\nExecStart={a.python} {r}/image-system/human-identity/bin/process_inbox.py\nTimeoutStartSec=50min\nNoNewPrivileges=true\nPrivateTmp=false\nUMask=0077\n'''
units['aag-human-identity-scene-bridge.service']=f'''[Unit]\nDescription=AAG Scene Identity Contract C worker\n[Service]\nType=oneshot\nWorkingDirectory={r}/image-system\nEnvironment=AAG_IMAGE_PROJECT_ROOT={r}/image-system\nEnvironment=AAG_HUMAN_IDENTITY_RUNTIME={r}/image-system/human-identity-scene\nEnvironment=AAG_HUMAN_IDENTITY_STATE_ROOT={s}/aag-human-identity-scene-state\nEnvironment=AAG_IMAGE_AGENT_STATE_ROOT={s}/aag-image-agent-state\nEnvironment=AAG_OUTPUT_ROOT={r}/outputs\nExecStart={a.python} {r}/image-system/human-identity-scene/bin/process_inbox.py\nTimeoutStartSec=50min\nNoNewPrivileges=true\nPrivateTmp=false\nUMask=0077\n'''
for name,text in units.items(): (o/name).write_text(text)
print(f'UNITS_RENDERED={len(units)} output={o}')
